-- ══════════════════════════════════════════════════════════════
-- AMES DE BRILLIANTE — Appwrite schema reference
-- This file is a REFERENCE only. The actual database, collections,
-- and attributes are auto-provisioned on first run by src/lib/appwrite.ts.
-- Do NOT run this file as SQL.
-- ══════════════════════════════════════════════════════════════

-- ── Database: "ames" ──
-- Created automatically by ensureReady()

-- ── Collection: jewelry_products ──
-- Private, staff-managed jewelry-engine product identity.
-- Appwrite document ID is productId; trader_id references traders.$id.
-- trader_id:          string(50), required
-- name:               string(255), required
-- category:           string(80), required
-- source_mode:        string(30), default "cloud_source_upload" (cloud_source_upload | operator_handoff)
-- source_files:       string(65535), JSON private bucket file references
-- source_hashes:      string(65535), JSON SHA-256 values for 3D sources
-- workflow_status:    string(50), submitted | processing | technical_review |
--                     visual_review | approved | published | rejected | revision_requested
-- asset_id:           string(100), required, one engine identity
-- unique index:       asset_id_unique on asset_id
-- revision_id:        string(150), current attached engine revision
-- pack_hash:          string(64), SHA-256 of delivery.zip
-- content_hash:       string(64), reviewed pack visuals/geometry and presentation identity
-- technical_pass:     boolean
-- visual_approval:    string(30), pending | approved | rejected
-- publication_status: string(30), review | published
-- review_reason:      string(2000)
-- status_history:     string(65535), JSON review transition log
-- verified_metadata:  string(10000), optional JSON; empty by default
-- created_at, updated_at: datetime

-- ── Collection: traders ──
-- name:       string(255), required
-- whatsapp:   string(255), default ""
-- licence:    string(255), default ""
-- portal_code: string(255), default ""
-- email:      string(255), default ""
-- status:     string(50), default "Pending"  (Pending | Active | Declined)
-- company:    string(255), default ""
-- country:    string(255), default ""
-- licence_photo: string(65535), default ""
-- created_at: datetime

-- ── Collection: stones ──
-- ref:          string(50), required
-- stone_type:   string(50), default "polished"
-- shape:        string(100), required
-- carat:        float, required, default 0
-- color:        string(50), required
-- clarity:      string(50), default ""
-- cut:          string(50), default ""
-- certification: string(50), default ""
-- category:     string(50), default ""
-- crystal_form: string(50), default ""
-- clarity_notes: string(2000), default ""
-- kp_status:    boolean, default false
-- price:        float, default 0  (0 = price on request / null)
-- status:       string(50), default "Available"  (Available | Reserved | Sold | Pending | Rejected)
-- photo:        string(2000), default ""
-- source:       string(50), default "Own stock"
-- trader_id:    string(50), default ""  (FK → traders.$id)
-- commission:   float, default 0
-- sale_price:   float, default 0  (0 = null)
-- photo_path:   string(500), default ""
-- listing_category: string(50), default "Polished"  (Rough | Polished | Jewelry)
-- created_at:   datetime

-- ── Collection: requests ──
-- date:           string(20), required
-- buyer_name:     string(255), default ""
-- company:        string(255), required
-- country:        string(255), default ""
-- contact:        string(255), required
-- type:           string(50), required
-- shape:          string(100), required
-- carat_min:      string(20), default ""
-- carat_max:      string(20), default ""
-- color:          string(50), required
-- clarity:        string(50), required
-- certification:  string(50), default ""
-- notes:          string(5000), default ""
-- kp_licence:     string(100), default ""
-- kp_country:     string(100), default ""
-- consent:        boolean, default false
-- declaration:    boolean, default false
-- consent_timestamp: string(50), default ""
-- mandate:        string(10000), default ""
-- status:         string(50), default "New"  (New | Sourcing | Quoted | Closed)
-- offer_text:     string(10000), default ""
-- offer_timestamp: string(50), default ""
-- created_at:     datetime

-- ── Collection: orders ──
-- stone_id:       string(50), required  (FK → stones.$id)
-- stone_ref:      string(50), required
-- buyer_name:     string(255), default ""
-- buyer_whatsapp: string(255), default ""
-- price:          float, default 0  (0 = null)
-- status:         string(50), default "Reserved"  (Reserved | Invoiced | Paid | Shipped | Closed)
-- created_at:     datetime

-- ── Collection: reports ──
-- trader_id:    string(50), required  (FK → traders.$id)
-- period_start: datetime, required
-- period_end:   datetime, required
-- report_date:  datetime, required
-- summary:      string(10000), default ""
-- data:         string(50000), default "{}"  (JSON)
-- created_at:   datetime

-- ── Collection: stone_status_log ──
-- stone_id:   string(50), required  (FK → stones.$id)
-- status:     string(50), required
-- reason:     string(2000), default ""
-- changed_at: datetime, required

-- ── Collection: models ──
-- name:                string(255), required
-- whatsapp:            string(255), default ""
-- instagram:           string(255), default ""
-- portal_code:         string(255), default ""
-- status:              string(50), default "Active"  (Active | Inactive)
-- monthly_video_quota: integer, default 30
-- monthly_base_fee:    float, default 200
-- commission_rate:     float, default 0.005
-- payment_method:      string(50), default ""
-- payment_details:     string(1000), default ""
-- total_paid:          float, default 0
-- created_at:          datetime

-- ── Collection: videos ──
-- video_url:         string(2000), required
-- caption:           string(500), default ""
-- stone_id:          string(50), default ""  (FK → stones.$id)
-- published:         boolean, default false
-- model_id:          string(50), default ""  (FK → models.$id)
-- status:            string(50), default "Live"  (Live | Pending)
-- tap_count:         integer, default 0
-- reserve_count:     integer, default 0
-- sales_count:       integer, default 0
-- sales_value:       float, default 0
-- commission_earned: float, default 0
-- created_at:        datetime

-- ── Storage Bucket: "media" ──
-- Public read/write
-- Max file size: 10 MB
-- Allowed extensions: jpg, jpeg, png, webp, gif
-- Created automatically by ensureReady()

-- ── Storage Bucket: "jewelry-sources" ──
-- Private: no public read/write permissions; server API key only.
-- Max file size: 250 MB
-- Allowed extensions: obj, glb, fbx, zip, jpg, jpeg, png, webp, pdf
