import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './jeweller-fixture.mjs';
import {createCustomerService} from '../src/lib/customer/service.mjs';
import {documentId} from '../src/lib/customer/appwrite.mjs';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a7XcAAAAASUVORK5CYII=','base64');
function setup(){const f=fixture(),files=new Map();let seq=0;f.gateway.uploadMedia=async({bytes,name})=>{const id='photo-'+(++seq);files.set(id,{bytes,name});return {$id:id};};f.gateway.deleteProfileImage=async(ref,userId)=>{assert.equal(ref.uploadedBy,userId);assert.ok(files.get(ref.fileId).name.startsWith('ames-profile-'+documentId(userId)));files.delete(ref.fileId);};f.gateway.stream=async ref=>new Response(files.get(ref.fileId).bytes);const service=createCustomerService(f.config,f.gateway);const upload=(who='alice',name='photo.png',type='image/png',bytes=png,extra=false)=>{const form=new FormData();form.set('file',new File([bytes],name,{type}));if(extra)form.set('userId','bob');return service.handle(new Request(f.config.origin+'/api/customer/profile-photo',{method:'POST',headers:{origin:f.config.origin,...(who?{cookie:'__Host-ames_customer='+who+'-session'}:{})},body:form}));};return {...f,files,upload};}
test('profile upload, replace, preferences and removal keep ownership and delete only old owned files',async()=>{const f=setup();let response=await f.upload();assert.equal(response.status,201);const first=(await response.json()).photo;assert.equal(first.uploadedBy,'alice');assert.equal(f.files.size,1);assert.deepEqual(Buffer.from(await(await f.request('profile-photo')).arrayBuffer()),png);assert.equal((await f.request('profile-photo','GET',undefined,'bob')).status,404);assert.equal((await f.request('profile-photo?userId=alice','GET',undefined,'bob')).status,404);assert.equal((await f.request('profile-photo','DELETE',{userId:'alice'},'bob')).status,400);assert.equal(f.files.size,1);await f.request('preferences','PUT',{sound:false});assert.equal((await f.gateway.get('profiles',documentId('alice'))).photo.fileId,first.fileId);response=await f.upload();assert.equal(response.status,201);const second=(await response.json()).photo;assert.notEqual(second.fileId,first.fileId);assert.ok(!f.files.has(first.fileId));assert.equal(f.files.size,1);assert.equal((await createCustomerService(f.config,f.gateway).handle(new Request(f.config.origin+'/api/customer/profile-photo',{method:'DELETE',headers:{origin:f.config.origin,cookie:'__Host-ames_customer=alice-session'},body:''}))).status,200);assert.equal(f.files.size,0);assert.equal((await f.request('profile-photo')).status,404);assert.equal((await f.gateway.get('profiles',documentId('alice'))).photo,null);});
test('photo upload rejects guests, arbitrary fields, spoofed images, unsupported MIME and oversized files',async()=>{const f=setup();assert.equal((await f.upload(null)).status,401);for(const [name,type,bytes] of [['bad.svg','image/svg+xml',png],['bad.exe','image/png',png],['bad.jpg','image/jpeg',png],['bad.png','image/png',Buffer.from('<script>bad</script>')],['big.png','image/png',Buffer.alloc(2*1024*1024+1)]])assert.equal((await f.upload('alice',name,type,bytes)).status,400);assert.equal((await f.upload('alice','photo.png','image/png',png,true)).status,400);assert.equal(f.files.size,0);});
test('failed profile update preserves previous photo and cleans new owned upload',async()=>{const f=setup();const first=(await(await f.upload()).json()).photo,put=f.gateway.put;f.gateway.put=async(k,id,v,...args)=>{if(k==='profiles')throw Error('fixture write failure');return put(k,id,v,...args);};assert.equal((await f.upload()).status,503);assert.equal(f.files.size,1);assert.ok(f.files.has(first.fileId));assert.equal((await f.gateway.get('profiles',documentId('alice'))).photo.fileId,first.fileId);});
test('portal denials and session navigation use the same verified application checks',async()=>{const f=fixture();assert.equal((await f.request('jewellers/me','GET',undefined,null)).status,401);assert.equal((await(await f.request('jewellers/me')).json()).reason,'APPLICATION_NOT_FOUND');for(const status of ['APPLIED','UNDER_REVIEW','REJECTED','SUSPENDED','UNKNOWN','VERIFIED']){await f.gateway.put('jewellers','atelier',{kind:'JEWELLER_APPLICATION',userId:'alice',email:'alice@example.test',verificationStatus:status});const session=await(await f.request('session')).json(),portal=await f.request('jewellers/me');assert.equal(session.access.jeweller,status==='VERIFIED');assert.equal(portal.status,status==='VERIFIED'?200:403);if(status!=='VERIFIED')assert.equal((await portal.json()).reason,status==='UNKNOWN'?'NOT_VERIFIED':status);}const original=f.gateway.user;f.gateway.user=async s=>({...await original(s),labels:['amesadmin']});assert.equal((await(await f.request('session','GET',undefined,'bob')).json()).access.admin,true);assert.equal((await f.request('admin/dashboard','GET',undefined,'bob')).status,200);assert.equal((await f.request('jewellers/me','GET',undefined,'bob')).status,403);});
