import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalAssetManifest} from '@ames/engine';
import {createCustomerService} from '../src/lib/customer/service.mjs';
import {customerConfig,assertConfigured} from '../src/lib/customer/config.mjs';
import {documentId} from '../src/lib/customer/appwrite.mjs';
function fixture(){
 let now=Date.now();const rows=new Map(),sessions=new Map([['alice-session','alice'],['bob-session','bob'],['admin-session','admin']]);
 const config=customerConfig({APPWRITE_ENDPOINT:'https://appwrite.example/v1',APPWRITE_PROJECT_ID:'test',APPWRITE_API_KEY:'test-only',AMES_APP_ORIGIN:'https://ames.example',ASSET_DELIVERY_SECRET:'test-only-'.repeat(8)});
 const gateway={async get(k,id){return rows.get(k+':'+id)||null;},async list(k,f={}){return [...rows].filter(([key,v])=>key.startsWith(k+':')&&Object.entries(f).every(([a,b])=>v[a]===b)).map(([,v])=>v);},async put(k,id,v,only=false){if(only&&rows.has(k+':'+id))throw {code:409};rows.set(k+':'+id,{id,...v});},async remove(k,id){rows.delete(k+':'+id);},async user(s){if(!sessions.has(s))throw {code:401};const id=sessions.get(s);return {$id:id,status:true,email:id+'@example.test',name:id,labels:id==='admin'?['amesadmin']:[]};},async login(email,password){if(password!=='test-password'||!['alice','bob'].includes(email.split('@')[0]))throw {code:401};const secret=email.split('@')[0]+'-session';return {secret,expire:new Date(now+3600000).toISOString()};},async register(){},async logout(s){sessions.delete(s);},async stream(){return new Response('test-glb-bytes');},async fileInfo(){return {$permissions:[],name:'test.glb'};},async health(){return true;}};
 for(const tier of ['PUBLIC','MEMBER','PREMIUM','COLLECTOR','PRIVATE']){const id=tier.toLowerCase();rows.set('catalog:'+documentId(id),{...canonicalAssetManifest.assets[0],id,accessTier:tier,status:'published',revision:1,storage:{bucketId:config.buckets.stones,fileId:'secret-storage-id'}});}
 let service=createCustomerService(config,gateway,()=>now);
 const request=(path,method='GET',data,who='alice',headers={})=>service.handle(new Request(new URL(path.startsWith('/')?path:'/api/customer/'+path,config.origin),{method,headers:{origin:config.origin,...(who?{cookie:'__Host-ames_customer='+who+'-session'}:{}),...headers},body:data===undefined?undefined:JSON.stringify(data)}));
 return {rows,gateway,config,request,advance:ms=>now+=ms,restart:()=>service=createCustomerService(config,gateway,()=>now),grant:async(userId,tier,effect='allow',assetId='')=>gateway.put('entitlements',documentId(userId,tier,assetId),{userId,tier,effect,assetId,expiresAt:new Date(now+3600000).toISOString()})};
}
test('configuration fails closed and permits only HTTPS or loopback Appwrite',()=>{assert.throws(()=>assertConfigured(customerConfig({})));const f=fixture();assertConfigured(f.config);assert.throws(()=>assertConfigured({...f.config,origin:'http://ames.example'}));});
test('one explicit HTTPS origin supports a deployment URL then a custom hostname and rejects the previous origin',async()=>{const f=fixture();for(const origin of ['https://deployment.example.test','https://custom.example.test']){const previous=f.config.origin;f.config.origin=origin;f.restart();assertConfigured(f.config);assert.equal((await f.request('favorites','PUT',{assetId:'public'})).status,200);assert.equal((await f.request('favorites','PUT',{assetId:'public'},'alice',{origin:previous})).status,403);}assert.throws(()=>assertConfigured({...f.config,origin:f.config.origin+'/path'}));});
test('Appwrite base64 session characters survive secure cookie encoding and reload',async()=>{const f=fixture(),opaque='fixture+session/value==',originalLogin=f.gateway.login,originalUser=f.gateway.user;f.gateway.login=async(...args)=>({...await originalLogin(...args),secret:opaque});f.gateway.user=async secret=>{assert.equal(secret,opaque);return originalUser('alice-session');};const r=await f.request('login','POST',{email:'alice@example.test',password:'test-password'},null);assert.equal(r.status,200);const cookie=r.headers.get('set-cookie').split(';')[0];assert.ok(cookie.includes(encodeURIComponent(opaque)));f.restart();const restored=await f.request('session','GET',undefined,null,{cookie});assert.equal((await restored.json()).user.id,'alice');});
test('real-session boundary: secure cookie, reload identity, logout revocation, bad credentials',async()=>{const f=fixture();const login=await f.request('login','POST',{email:'alice@example.test',password:'test-password'},null);assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly; SameSite=Lax.*Secure/);f.restart();assert.equal((await (await f.request('session')).json()).user.id,'alice');assert.equal((await f.request('login','POST',{email:'alice@example.test',password:'incorrect'},null)).status,401);assert.equal((await f.request('logout','POST',{})).status,200);assert.equal((await f.request('session')).status,401);});
test('favorites, saved jewelry, saved stone, designs and preferences persist across service reload and isolate owners',async()=>{const f=fixture();for(const [path,data] of [['favorites',{assetId:'public',userId:'bob'}],['saved',{assetId:'public'}],['designs',{designId:'design-1',spec:{category:'ring'},ownerId:'bob'}],['preferences',{sound:false}]])assert.equal((await f.request(path,'PUT',data)).status,200);f.restart();const state=await (await f.request('state')).json();assert.equal(state.favorites[0].userId,'alice');assert.equal(state.saved[0].kind,'stone');assert.equal(state.designs[0].userId,'alice');assert.equal(state.profile.preferences.sound,false);const bob=await (await f.request('state','GET',undefined,'bob')).json();assert.equal(bob.favorites.length,0);assert.equal(bob.saved.length,0);assert.equal(bob.designs.length,0);await f.request('favorites','DELETE',{assetId:'public'},'bob');assert.equal((await (await f.request('state')).json()).favorites.length,1);const asset=f.rows.get('catalog:'+documentId('public'));asset.category='ring';await f.request('saved','PUT',{assetId:'public'});assert.equal((await (await f.request('state')).json()).saved[0].kind,'jewelry');});
test('all five tiers: guest/member, exact paid tier, private explicit grant, explicit deny wins',async()=>{const f=fixture();for(const tier of ['public','member','premium','collector','private'])assert.equal((await (await f.request('access/'+tier,'GET',undefined,null)).json()).granted,tier==='public');assert.equal((await (await f.request('access/member')).json()).granted,true);await f.grant('alice','PREMIUM');assert.equal((await (await f.request('access/premium')).json()).granted,true);assert.equal((await (await f.request('access/collector')).json()).granted,false);assert.equal((await (await f.request('access/private')).json()).granted,false);await f.grant('alice','PRIVATE','allow','private');assert.equal((await (await f.request('access/private')).json()).granted,true);await f.grant('alice','PREMIUM','deny','premium');assert.equal((await (await f.request('access/premium')).json()).granted,false);});
test('protected delivery is session-bound, short-lived, tamper resistant and rechecks revocation',async()=>{const f=fixture();assert.equal((await f.request('assets/premium.glb','GET',undefined,null)).status,401);assert.equal((await f.request('delivery/premium','POST',{})).status,403);await f.grant('alice','PREMIUM');const lease=await (await f.request('delivery/premium','POST',{})).json();const path=new URL(lease.url).pathname+new URL(lease.url).search;assert.equal(await (await f.request(path)).text(),'test-glb-bytes');assert.equal((await f.request(path,'GET',undefined,'bob')).status,403);assert.equal((await f.request(path+'x')).status,403);await f.grant('alice','PREMIUM','deny');assert.equal((await f.request(path)).status,403);await f.grant('alice','PREMIUM');f.advance(61000);assert.equal((await f.request(path)).status,403);});
test('private catalog hides unauthorized records and never exposes storage references',async()=>{const f=fixture();const text=await (await f.request('catalog')).text();assert.ok(!text.includes('secret-storage-id'));assert.ok(!text.includes('bucketId'));assert.ok(!JSON.parse(text).assets.some(a=>a.id==='private'));});
test('CSRF, forged administrator and forged server analytics are rejected',async()=>{const f=fixture();assert.equal((await f.request('favorites','PUT',{assetId:'public'},'alice',{origin:'https://evil.example'})).status,403);assert.equal((await f.request('admin/entitlements','PUT',{userId:'alice',tier:'PREMIUM'})).status,403);assert.equal((await f.request('preferences','PUT',{admin:true})).status,400);assert.equal((await f.request('events','POST',{type:'ACCESS_GRANTED'})).status,400);});
test('administrator subscription state persists and expiry revokes access',async()=>{const f=fixture();assert.equal((await f.request('admin/subscriptions','PUT',{userId:'alice',tier:'COLLECTOR',status:'active',expiresAt:new Date(Date.now()+10000).toISOString()},'admin')).status,200);f.restart();assert.equal((await (await f.request('access/collector')).json()).granted,true);assert.equal((await (await f.request('state')).json()).subscriptions[0].status,'active');f.advance(20000);assert.equal((await (await f.request('access/collector')).json()).granted,false);});
test('backend outages fail closed without leaking provider errors',async()=>{const f=fixture();f.gateway.user=async()=>{throw new Error('secret-key-value');};const r=await f.request('state');assert.equal(r.status,503);assert.ok(!(await r.text()).includes('secret-key-value'));});
test('authentication limiter survives service reconstruction',async()=>{const f=fixture();for(let i=0;i<10;i++){assert.equal((await f.request('login','POST',{email:'alice@example.test',password:'incorrect'},null)).status,401);f.restart();}assert.equal((await f.request('login','POST',{email:'alice@example.test',password:'test-password'},null)).status,429);});
