import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalAssetManifest} from '@ames/engine';
import {createCustomerService} from '../src/lib/customer/service.mjs';
import {customerConfig,assertConfigured} from '../src/lib/customer/config.mjs';
import {documentId} from '../src/lib/customer/appwrite.mjs';
function fixture(){
 let now=Date.now();const rows=new Map(),sessions=new Map([['alice-session','alice'],['bob-session','bob'],['admin-session','admin']]);
 const config=customerConfig({APPWRITE_ENDPOINT:'https://appwrite.example/v1',APPWRITE_PROJECT_ID:'test',APPWRITE_API_KEY:'test-only',AMES_APP_ORIGIN:'https://ames.example',ASSET_DELIVERY_SECRET:'test-only-'.repeat(8)});
 const gateway={async get(k,id){return rows.get(k+':'+id)||null;},async list(k,f={}){return [...rows].filter(([key,v])=>key.startsWith(k+':')&&Object.entries(f).every(([a,b])=>v[a]===b)).map(([,v])=>v);},async put(k,id,v,only=false){if(only&&rows.has(k+':'+id))throw {code:409};rows.set(k+':'+id,{id,...v});},async remove(k,id){rows.delete(k+':'+id);},async user(s){if(!sessions.has(s))throw {code:401};const id=sessions.get(s);return {$id:id,status:true,email:id+'@example.test',name:id,labels:id==='admin'?['amesadmin']:[]};},async login(email,password){if(password!=='test-password'||!['alice','bob'].includes(email.split('@')[0]))throw {code:401};const secret=email.split('@')[0]+'-session';return {secret,expire:new Date(now+3600000).toISOString()};},async register(){},async logout(s){sessions.delete(s);},async stream(){return new Response('test-glb-bytes');},async fileInfo(){return {$permissions:[],name:'test.glb'};},async health(){return true;}};
 for(const tier of ['PUBLIC','MEMBER','PREMIUM','COLLECTOR','PRIVATE']){const id=tier.toLowerCase();rows.set('catalog:'+documentId(id),{...canonicalAssetManifest.assets[0],id,accessTier:tier,status:'published',revision:1,storage:{bucketId:config.buckets.stones,fileId:'secret-storage-id'}});}
 let service=createCustomerService(config,gateway,()=>now);
 const request=(path,method='GET',data,who='alice',headers={})=>service.handle(new Request(new URL(path.startsWith('/')?path:'/api/customer/'+path,config.origin),{method,headers:{origin:config.origin,...(who?{cookie:'__Host-ames_customer='+who+'-session'}:{}),...headers},body:data===undefined?undefined:JSON.stringify(data)}));
 return {rows,gateway,config,request,advance:ms=>now+=ms,restart:()=>service=createCustomerService(config,gateway,()=>now),grant:async(userId,tier,effect='allow',assetId='')=>gateway.put('entitlements',documentId(userId,tier,assetId),{userId,tier,effect,assetId,expiresAt:new Date(now+3600000).toISOString()})};
}
test('configuration fails closed and permits only HTTPS or loopback Appwrite',()=>{assert.throws(()=>assertConfigured(customerConfig({})));const f=fixture();assertConfigured(f.config);assert.throws(()=>assertConfigured({...f.config,origin:'http://ames.example'}));});
test('one explicit HTTPS origin supports a deployment URL then a custom hostname and rejects the previous origin',async()=>{const f=fixture();for(const origin of ['https://deployment.example.test','https://custom.example.test']){const previous=f.config.origin;f.config.origin=origin;f.restart();assertConfigured(f.config);assert.equal((await f.request('favorites','PUT',{assetId:'public'})).status,200);assert.equal((await f.request('favorites','PUT',{assetId:'public'},'alice',{origin:previous})).status,403);}assert.throws(()=>assertConfigured({...f.config,origin:f.config.origin+'/path'}));});
test('Appwrite base64 session characters survive secure cookie encoding and reload',async()=>{const f=fixture(),opaque='fixture+session/value==',originalLogin=f.gateway.login,originalUser=f.gateway.user;f.gateway.login=async(...args)=>({...await originalLogin(...args),secret:opaque});f.gateway.user=async secret=>{assert.equal(secret,opaque);return originalUser('alice-session');};const r=await f.request('login','POST',{email:'alice@example.test',password:'test-password'},null);assert.equal(r.status,200);const cookie=r.headers.get('set-cookie').split(';')[0];assert.ok(cookie.includes(encodeURIComponent(opaque)));f.restart();const restored=await f.request('session','GET',undefined,null,{cookie});assert.equal((await restored.json()).user.id,'alice');});
test('real-session boundary: secure cookie, reload identity, logout revocation, bad credentials',async()=>{const f=fixture();const login=await f.request('login','POST',{email:'alice@example.test',password:'test-password'},null);assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly; SameSite=Lax.*Secure/);f.restart();assert.equal((await (await f.request('session')).json()).user.id,'alice');assert.equal((await f.request('login','POST',{email:'alice@example.test',password:'incorrect'},null)).status,401);assert.equal((await f.request('logout','POST',{})).status,200);assert.equal((await f.request('session')).status,401);});
test('favorites, saved jewelry, saved stone, designs and preferences persist across service reload and isolate owners',async()=>{const f=fixture();for(const [path,data] of [['favorites',{assetId:'public',userId:'bob'}],['saved',{assetId:'public'}],['designs',{designId:'design-1',spec:{category:'ring'},ownerId:'bob'}],['preferences',{sound:false}]])assert.equal((await f.request(path,'PUT',data)).status,200);f.restart();const state=await (await f.request('state')).json();assert.equal(state.favorites[0].userId,'alice');assert.equal(state.saved[0].kind,'stone');assert.equal(state.designs[0].userId,'alice');assert.equal(state.profile.preferences.sound,false);const bob=await (await f.request('state','GET',undefined,'bob')).json();assert.equal(bob.favorites.length,0);assert.equal(bob.saved.length,0);assert.equal(bob.designs.length,0);await f.request('favorites','DELETE',{assetId:'public'},'bob');assert.equal((await (await f.request('state')).json()).favorites.length,1);const asset=f.rows.get('catalog:'+documentId('public'));asset.category='ring';await f.request('saved','PUT',{assetId:'public'});assert.equal((await (await f.request('state')).json()).saved[0].kind,'jewelry');});
test('all five tiers: guest/member, exact paid tier, private explicit grant, explicit deny wins',async()=>{const f=fixture();for(const tier of ['public','member','premium','collector','private'])assert.equal((await (await f.request('access/'+tier,'GET',undefined,null)).json()).granted,tier==='public');assert.equal((await (await f.request('access/member')).json()).granted,true);await f.grant('alice','PREMIUM');assert.equal((await (await f.request('access/premium')).json()).granted,true);assert.equal((await (await f.request('access/collector')).json()).granted,false);assert.equal((await (await f.request('access/private')).json()).granted,false);await f.grant('alice','PRIVATE','allow','private');assert.equal((await (await f.request('access/private')).json()).granted,true);await f.grant('alice','PREMIUM','deny','premium');assert.equal((await (await f.request('access/premium')).json()).granted,false);});
test('protected delivery is session-bound, short-lived, tamper resistant and rechecks revocation',async()=>{const f=fixture();assert.equal((await f.request('assets/premium.glb','GET',undefined,null)).status,401);assert.equal((await f.request('delivery/premium','POST',{})).status,403);await f.grant('alice','PREMIUM');const lease=await (await f.request('delivery/premium','POST',{})).json();const path=new URL(lease.url).pathname+new URL(lease.url).search;assert.equal(await (await f.request(path)).text(),'test-glb-bytes');assert.equal((await f.request(path,'GET',undefined,'bob')).status,403);assert.equal((await f.request(path+'x')).status,403);await f.grant('alice','PREMIUM','deny');assert.equal((await f.request(path)).status,403);await f.grant('alice','PREMIUM');f.advance(61000);assert.equal((await f.request(path)).status,403);});
test('private catalog hides unauthorized records and never exposes storage references',async()=>{const f=fixture();const text=await (await f.request('catalog')).text();assert.ok(!text.includes('secret-storage-id'));assert.ok(!text.includes('bucketId'));assert.ok(!JSON.parse(text).assets.some(a=>a.id==='private'));});
test('CSRF, forged administrator and forged server analytics are rejected',async()=>{const f=fixture();assert.equal((await f.request('favorites','PUT',{assetId:'public'},'alice',{origin:'https://evil.example'})).status,403);assert.equal((await f.request('admin/entitlements','PUT',{userId:'alice',tier:'PREMIUM'})).status,403);assert.equal((await f.request('preferences','PUT',{admin:true})).status,400);assert.equal((await f.request('events','POST',{type:'ACCESS_GRANTED'})).status,400);assert.equal((await f.request('events','POST',{type:'RESERVE_REQUEST',assetId:'public'})).status,400);});
test('reserve requests attach product, account and pending status without claiming confirmation',async()=>{const f=fixture();const response=await f.request('reserve','POST',{assetId:'public',conversationId:'sealed-conversation',context:'Please hold this for me'});assert.equal(response.status,200);assert.deepEqual(await response.json(),{ok:true,status:'PENDING',assetId:'public'});const events=await f.gateway.list('events',{userId:'alice'});assert.equal(events.length,1);assert.equal(events[0].kind,'RESERVE_REQUEST');assert.equal(events[0].status,'PENDING');assert.equal(events[0].conversationId,'sealed-conversation');});
test('guest reserve is recorded without a user identity and handoff stays unconfigured until desk contact is supplied',async()=>{const f=fixture();const reserve=await f.request('reserve','POST',{assetId:'public'},null);assert.equal(reserve.status,200);const handoff=await f.request('handoff','POST',{assetId:'public',intent:'enquiry',context:'availability'},null);assert.equal(handoff.status,200);assert.equal((await handoff.json()).whatsappUrl,null);const events=await f.gateway.list('events',{userId:''});assert.equal(events.length,2);assert.ok(events.every(e=>['RESERVE_REQUEST','DESK_HANDOFF'].includes(e.kind)));});
test('guest identity persists memory and upgrades idempotently into an account',async()=>{const f=fixture();
 const first=await f.request('session','GET',undefined,null);assert.equal(first.status,200);assert.equal((await first.clone().json()).guest,true);const guestCookie=first.headers.get('set-cookie').split(';')[0];
 assert.equal((await f.request('preferences','PUT',{memory:{categories:['ring'],shapes:['oval'],metals:['platinum'],budgetRange:{latest:6000},language:'en'}},null,{cookie:guestCookie})).status,200);
 assert.equal((await f.request('favorites','PUT',{assetId:'public'},null,{cookie:guestCookie})).status,200);
 const restored=await f.request('state','GET',undefined,null,{cookie:guestCookie});assert.equal((await restored.json()).profile.preferences.memory.shapes[0],'oval');
 const login=await f.request('login','POST',{email:'alice@example.test',password:'test-password'},null,{cookie:guestCookie});assert.equal(login.status,200);const authCookie=login.headers.get('set-cookie').split(';')[0];
 const accountState=await f.request('state','GET',undefined,null,{cookie:authCookie});const state=await accountState.json();assert.equal(state.favorites.length,1);assert.equal(state.profile.preferences.memory.metals[0],'platinum');
 const guestProfile=await f.gateway.get('profiles',documentId('guest:'+JSON.parse(Buffer.from(guestCookie.split('.')[0].split('=')[1],'base64url').toString()).guestId));assert.equal(guestProfile.accountState,'merged');
 const again=await f.request('login','POST',{email:'alice@example.test',password:'test-password'},null,{cookie:guestCookie});assert.equal(again.status,200);assert.equal((await f.gateway.list('favorites',{userId:'alice'})).length,1);
});
test('pre-inventory sourcing requests capture a bounded preference profile and remain open',async()=>{const f=fixture();const response=await f.request('request','POST',{profile:{category:'ring',budget:7000,metal:'platinum',shape:'oval'},notes:'engagement',conversationId:'conversation-1'});assert.equal(response.status,200);assert.deepEqual(await response.json(),{ok:true,status:'OPEN'});const events=await f.gateway.list('events',{userId:'alice'});assert.equal(events[0].kind,'SOURCING_REQUEST');assert.equal(events[0].status,'OPEN');assert.equal(events[0].profile.shape,'oval');});
test('administrators can review and update sourcing requests while customers cannot',async()=>{const f=fixture();await f.request('request','POST',{profile:{category:'ring'},notes:'desk review'},'alice');const created=(await f.gateway.list('events',{userId:'alice'}))[0];assert.equal((await f.request('admin/requests','GET',undefined,'admin')).status,200);assert.equal((await f.request('admin/requests','GET',undefined,'alice')).status,403);const updated=await f.request('admin/requests','PUT',{requestId:created.id,status:'CANCELLED',notes:'Customer cancelled',matchingRefs:[]},'admin');assert.equal(updated.status,200);const stored=await f.gateway.get('events',created.id);assert.equal(stored.status,'CANCELLED');assert.equal(stored.notes,'Customer cancelled');});
test('jeweller onboarding is private, duplicate-safe and drives verified-only bespoke matching',async()=>{const f=fixture();const application={businessName:'Atelier One',legalEntityName:'Atelier One (Pty) Ltd',country:'Botswana',city:'Gaborone',contactPerson:'Alice',email:'alice@example.test',phone:'+267 71 222 333',website:'https://www.atelier.example',socialLinks:['https://instagram.com/atelier'],languages:['English'],countriesServed:['Botswana'],categories:['ring'],diamondShapes:[],metals:['platinum'],priceBands:[],bespoke:true,looseDiamonds:false,certificationSupport:[],provenance:undefined,reserve:undefined,delivery:true,leadTimes:'Approximately four weeks',afterSales:true,returns:undefined};
 const created=await f.request('jewellers/apply','POST',application,null);assert.equal(created.status,201);const result=await created.json();assert.equal(result.status,'APPLIED');
 assert.equal((await f.request('jewellers/apply','POST',{...application,businessName:'Unrelated display name',email:'other@example.test',phone:'+267 99 999 999'},null)).status,409);
 assert.equal((await f.request('admin/jewellers','GET',undefined,'alice')).status,403);const adminRows=await (await f.request('admin/jewellers','GET',undefined,'admin')).json();assert.equal(adminRows.applications.length,1);assert.equal(adminRows.applications[0].capabilities.provenance,undefined);
 assert.equal((await f.request('jewellers/me','GET',undefined,'bob')).status,403);assert.equal((await f.request('jewellers/me','GET',undefined,'alice')).status,403);
 for(const status of ['UNDER_REVIEW','REJECTED'])assert.equal((await f.request('admin/jewellers','PUT',{applicationId:result.applicationId,status,internalNotes:'Private diligence'},'admin')).status,200);
 let sourcing=await f.request('request','POST',{profile:{category:'ring',metal:'platinum',shape:'asscher',sourcing_intent:true}},'alice');assert.equal(sourcing.status,200);let event=(await f.gateway.list('events',{userId:'alice'})).find(v=>v.kind==='SOURCING_REQUEST');assert.equal(event.matches.length,0);
 assert.equal((await f.request('admin/jewellers','PUT',{applicationId:result.applicationId,status:'UNDER_REVIEW'},'admin')).status,200);
 const verified=await (await f.request('admin/jewellers','PUT',{applicationId:result.applicationId,status:'VERIFIED',internalNotes:'Approved privately'},'admin')).json();assert.equal(verified.matchingEligible,true);assert.ok(verified.verificationDate);
 sourcing=await f.request('request','POST',{profile:{category:'ring',metal:'platinum',shape:'asscher',sourcing_intent:true}},'alice');assert.equal(sourcing.status,200);event=(await f.gateway.list('events',{userId:'alice'})).filter(v=>v.kind==='SOURCING_REQUEST').at(-1);assert.equal(event.matches[0].jewellerId,result.applicationId);assert.ok(event.matches[0].reasons.includes('bespoke sourcing capability'));
 assert.equal((await f.request('admin/jewellers','PUT',{applicationId:result.applicationId,status:'SUSPENDED'},'admin')).status,200);await f.request('request','POST',{profile:{category:'ring',sourcing_intent:true}},'alice');event=(await f.gateway.list('events',{userId:'alice'})).filter(v=>v.kind==='SOURCING_REQUEST').at(-1);assert.equal(event.matches.length,0);
 assert.equal((await f.request('jewellers/me','GET',undefined,'alice')).status,403);
});
test('administrator subscription state persists and expiry revokes access',async()=>{const f=fixture();assert.equal((await f.request('admin/subscriptions','PUT',{userId:'alice',tier:'COLLECTOR',status:'active',expiresAt:new Date(Date.now()+10000).toISOString()},'admin')).status,200);f.restart();assert.equal((await (await f.request('access/collector')).json()).granted,true);assert.equal((await (await f.request('state')).json()).subscriptions[0].status,'active');f.advance(20000);assert.equal((await (await f.request('access/collector')).json()).granted,false);});
test('backend outages fail closed without leaking provider errors',async()=>{const f=fixture();f.gateway.user=async()=>{throw new Error('secret-key-value');};const r=await f.request('state');assert.equal(r.status,503);assert.ok(!(await r.text()).includes('secret-key-value'));});
test('authentication limiter survives service reconstruction',async()=>{const f=fixture();for(let i=0;i<10;i++){assert.equal((await f.request('login','POST',{email:'alice@example.test',password:'incorrect'},null)).status,401);f.restart();}assert.equal((await f.request('login','POST',{email:'alice@example.test',password:'test-password'},null)).status,429);});

test('verified inventory approval, controlled categories, SAME catalog and handoff share the product ID',async()=>{
 const f=fixture();const app={id:'atelier',kind:'JEWELLER_APPLICATION',businessName:'Real atelier',email:'alice@example.test',verificationStatus:'APPLIED'};
 await f.gateway.put('jewellers','atelier',app);
 assert.equal((await f.request('jewellers/inventory','POST',{name:'Ring',category:'Rings'})).status,403);
 await f.gateway.put('jewellers','atelier',{...app,verificationStatus:'VERIFIED'});
 assert.equal((await f.request('jewellers/inventory','POST',{name:'Invalid',category:'Unknown'})).status,400);
 const ids=[];
 for(const [category,key] of [['Rings','ring'],['Watches','watch'],['Bracelets','bracelet'],['Necklaces','necklace'],['Earrings','earring']]){
  const submitted=await f.request('jewellers/inventory','POST',{name:category,category,metal:'18k white gold',price:1000,images:['https://example.test/real.jpg']});assert.equal(submitted.status,201);
  const {item}=await submitted.json();ids.push(item.id);assert.equal(item.inventoryStatus,'DRAFT');assert.equal(item.jewellerId,'atelier');assert.equal((await f.request('jewellers/inventory/'+item.id,'PUT',{action:'submit',revision:item.revision})).status,200);
  assert.equal((await (await f.request('catalog')).json()).assets.some(a=>a.id===item.id),false);
  assert.equal((await f.request('admin/inventory','PUT',{inventoryId:item.id,status:'APPROVED'})).status,403);
  assert.equal((await f.request('admin/inventory','PUT',{inventoryId:item.id,status:'APPROVED'},'admin')).status,200);
  const published=(await (await f.request('catalog')).json()).assets.find(a=>a.id===item.id);assert.equal(published.category,key);assert.equal(published.jewellerId,'atelier');assert.equal(published.price,1000);
 }
 for(const status of ['DRAFT','PENDING_REVIEW','REJECTED','CHANGES_REQUESTED','SUSPENDED','SOLD','ARCHIVED']){
  await f.request('admin/inventory','PUT',{inventoryId:ids[0],status},'admin');assert.equal((await (await f.request('catalog')).json()).assets.some(a=>a.id===ids[0]),false);assert.equal((await f.request('reserve','POST',{assetId:ids[0]})).status,404);
 }
 await f.request('handoff','POST',{assetId:ids[4],intent:'reserve'});await f.request('reserve','POST',{assetId:ids[4]});
 const leads=(await f.gateway.list('events')).filter(e=>e.kind==='INVENTORY_LEAD');assert.equal(leads.length,2);assert.ok(leads.every(e=>e.jewellerId==='atelier'&&e.inventoryId===ids[4]));
});
