'use client';
import {FormEvent,useState} from 'react';

const input='mt-2 w-full border-0 border-b border-white/25 bg-transparent px-0 py-3 text-sm !font-light text-white outline-none transition-colors placeholder:text-white/35 focus:border-white/60';
const fields=[['businessName','Business name *'],['legalEntityName','Legal entity name *'],['country','Country'],['city','City'],['contactPerson','Contact person'],['email','Email *','email'],['phone','Phone *','tel'],['website','Website','url'],['socialLinks','Social links (comma-separated)'],['languages','Languages (comma-separated)'],['countriesServed','Countries served (comma-separated)'],['categories','Categories (comma-separated)'],['diamondShapes','Diamond shapes (comma-separated)'],['metals','Metals (comma-separated)'],['certificationSupport','Certification support (comma-separated)'],['leadTimes','Approximate lead times'],['priceBands','Price bands (for example USD 2,000–5,000)']] as const;
const choices=[['bespoke','Bespoke / custom capability'],['looseDiamonds','Loose diamond capability'],['provenance','Provenance information capability'],['reserve','Reserve capability'],['delivery','Delivery capability'],['afterSales','After-sales support'],['returns','Return policy available']] as const;

export default function JewellerApplicationForm(){
 const [state,setState]=useState<'idle'|'busy'|'done'|'error'>('idle'),[message,setMessage]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setState('busy');setMessage('');const form=new FormData(e.currentTarget),body:Record<string,unknown>={};for(const [key] of fields){const value=String(form.get(key)||'').trim();if(['socialLinks','languages','countriesServed','categories','diamondShapes','metals','certificationSupport'].includes(key))body[key]=value?value.split(',').map(v=>v.trim()).filter(Boolean):[];else if(key==='priceBands'){if(value){const nums=value.match(/[\d,.]+/g)?.map(v=>Number(v.replaceAll(',',''))).filter(Number.isFinite)||[];body.priceBands=[{...(nums[0]!==undefined?{min:nums[0]}:{}),...(nums[1]!==undefined?{max:nums[1]}:{}),currency:value.match(/\b[A-Z]{3}\b/)?.[0]}];}else body.priceBands=[];}else body[key]=value;}for(const [key] of choices){const value=form.get(key);body[key]=value==='yes'?true:value==='no'?false:undefined;}try{const r=await fetch('/api/customer/jewellers/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json();if(!r.ok)throw new Error(data.error||'Application could not be submitted');setState('done');setMessage('Application received. AMES will review it privately.');e.currentTarget.reset();}catch(error){setState('error');setMessage(error instanceof Error?error.message:'Application could not be submitted');}}
 return <form onSubmit={submit} className="mt-16 grid gap-x-10 gap-y-9 sm:mt-24 sm:grid-cols-2 sm:gap-y-11">
  {fields.map(([key,label,type])=><label key={key} className={`!font-light ${['socialLinks','countriesServed','categories','certificationSupport','leadTimes','priceBands'].includes(key)?'sm:col-span-2':''}`}><span className="text-[11px] !font-light tracking-[.025em] text-white">{label}</span><input className={input} name={key} type={type||'text'} required={label.endsWith('*')} /></label>)}
  <fieldset className="mt-5 grid gap-x-10 gap-y-9 border-t border-white/15 pt-12 sm:col-span-2 sm:grid-cols-2 sm:gap-y-11"><legend className="mb-1 text-[11px] !font-light uppercase tracking-[.18em] text-[#aeb6bf]">Capabilities — choose unknown when not confirmed</legend>{choices.map(([key,label])=><label key={key} className="!font-light"><span className="block text-[11px] !font-light tracking-[.025em] text-white">{label}</span><select name={key} defaultValue="unknown" className={input}><option value="unknown">Unknown</option><option value="yes">Yes</option><option value="no">No</option></select></label>)}</fieldset>
  <div className="mt-5 border-t border-white/15 pt-10 sm:col-span-2 sm:mt-9 sm:pt-12"><button disabled={state==='busy'||state==='done'} className="border border-white/35 bg-transparent px-7 py-3 text-[11px] font-normal uppercase tracking-[.16em] text-white transition-colors hover:border-white/70 hover:bg-white/[.04] disabled:opacity-50">{state==='busy'?'Submitting…':state==='done'?'Submitted':'Submit application'}</button>{message&&<p role="status" className={`mt-4 text-sm font-light ${state==='error'?'text-[#d3b4b8]':'text-[#cbd1d7]'}`}>{message}</p>}<p className="mt-7 max-w-xl text-[11px] font-light leading-5 text-[#8f98a2]">Submitted information is used for network review and matching eligibility. Internal review notes are never shared publicly.</p></div>
 </form>
}
