"use client";
import {useState} from 'react';
import {customerRequest} from '@/components/CustomerState';
import styles from './portal.module.css';
type Row=Record<string,any>;
const groups:Record<string,[string,string][]>={Basic:[['name','Product name'],['category','Category'],['description','Description'],['sku','SKU / reference']],Pricing:[['price','Price'],['currency','Currency']],Availability:[['availability','Availability'],['stockQuantity','Stock quantity'],['leadTime','Delivery timing']],Material:[['metal','Metal'],['setting','Setting / style']], 'Stone data (where applicable)':[['diamondShape','Shape'],['carat','Carat'],['color','Color'],['clarity','Clarity'],['cut','Cut'],['certification','Certification'],['certificationReference','Certificate number']], 'Source / trust':[['provenanceNotes','Provenance'],['origin','Origin / source'],['certificationNotes','Certification notes']]};
const numeric=['price','stockQuantity','carat'];
export default function InventorySection({initialItem,onSaved,onCancel}:{initialItem?:Row;onSaved:(item:Row)=>void;onCancel:()=>void}){
 const [form,setForm]=useState<Row>(()=>Object.fromEntries(Object.values(groups).flat().map(([k])=>[k,initialItem?.[k]??(k==='category'?'Rings':k==='currency'?'USD':'')]))),[media,setMedia]=useState<Row[]>(initialItem?.media||[]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function upload(files:FileList|null,kind:string,main=false){if(!files?.length)return;setBusy(true);setMessage('');try{const added:Row[]=[];for(const file of Array.from(files)){if(file.size>4*1024*1024)throw new Error('Each file must be 4 MiB or smaller.');const data=new FormData();data.set('file',file);data.set('kind',kind);const r=await fetch('/api/customer/jewellers/media',{method:'POST',body:data}),result=await r.json();if(!r.ok)throw new Error(result.error||'Upload failed');added.push(result);}setMedia(current=>kind==='image'?(main?[...added,...current]:[...current,...added]):[...current.filter(m=>m.kind!==kind),...added]);}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 async function save(action:string){setBusy(true);setMessage('');try{const b:Row={...form,action,media:media.map(m=>({fileId:m.fileId,kind:m.kind})),images:initialItem?.media?.some((m:Row)=>m.kind==='image')?[]:initialItem?.images||[],video:initialItem?.media?.some((m:Row)=>m.kind==='video')?'':initialItem?.video||'',glb:initialItem?.media?.some((m:Row)=>m.kind==='glb')?'':initialItem?.glb||''};for(const k of numeric)b[k]=form[k]===''?undefined:Number(form[k]);if(initialItem)b.revision=initialItem.revision;const result=await customerRequest('jewellers/inventory'+(initialItem?'/'+initialItem.id:''),initialItem?'PUT':'POST',b);onSaved(result.item);}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 return <section className={styles.panel}><div className={styles.sectionHead}><div><h2>{initialItem?'Edit inventory':'Upload jewelry'}</h2><p className={styles.muted}>Save privately, then submit for AMES review. Only admin approval makes a piece public.</p></div><button onClick={onCancel}>Back to inventory</button></div><form className={styles.form} onSubmit={e=>{e.preventDefault();save('save');}}><fieldset disabled={busy} style={{border:0,padding:0}}>
 {Object.entries(groups).map(([group,fields])=><fieldset key={group} style={{marginBottom:20}}><legend>{group}</legend><div className={styles.fields}>{fields.map(([key,label])=><label className={styles.field} key={key}><span>{label}</span>{key==='category'?<select aria-label={label} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}>{['Rings','Watches','Bracelets','Necklaces','Earrings'].map(c=><option key={c}>{c}</option>)}</select>:['description','provenanceNotes','certificationNotes'].includes(key)?<textarea aria-label={label} maxLength={2000} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input aria-label={label} required={key==='name'} type={numeric.includes(key)?'number':'text'} min={numeric.includes(key)?0:undefined} step={key==='stockQuantity'?1:'any'} maxLength={500} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}</div></fieldset>)}
 <fieldset><legend>Media</legend><p className={styles.muted}>Private Appwrite uploads, up to 4 MiB each. The first image is the main image. Stone fields are optional.</p><div className={styles.fields}>{[['Main image','image',false],['Additional images','image',true],['Video (optional)','video',false],['GLB / 3D asset (optional)','glb',false]].map(([label,kind,multiple],i)=><label className={styles.field} key={String(label)}><span>{label}</span><input aria-label={String(label)} type="file" multiple={Boolean(multiple)} accept={kind==='image'?'image/png,image/jpeg,image/webp':kind==='video'?'video/mp4,video/webm,video/quicktime':'.glb'} onChange={e=>upload(e.target.files,String(kind),i===0)}/></label>)}</div><div className={styles.mediaList}>{media.map((m,i)=><div key={m.fileId}>{m.kind==='image'?<img src={'/api/customer/jewellers/media/'+m.fileId} alt={i===0?'Main image':'Additional image'}/>:m.kind==='video'?<video controls playsInline src={'/api/customer/jewellers/media/'+m.fileId}/>:<p>GLB attached</p>}<div className={styles.actions}>{m.kind==='image'&&i>0&&<button type="button" onClick={()=>setMedia([m,...media.filter((_,j)=>j!==i)])}>Make main</button>}<button type="button" onClick={()=>setMedia(media.filter((_,j)=>j!==i))}>Remove</button></div></div>)}</div></fieldset>
 {message&&<p role="alert" className={styles.message}>{message}</p>}<div className={styles.actions}><button type="submit">{busy?'Saving...':'Save draft'}</button>{initialItem&&<button type="button" onClick={()=>save('submit')}>Submit for review</button>}</div></fieldset></form></section>;
}
