"use client";
import {useEffect,useState} from 'react';
type Item=Record<string,unknown>;
export default function InventorySection({enabled}:{enabled:boolean}){const [items,setItems]=useState<Item[]>([]),[message,setMessage]=useState('');const [form,setForm]=useState<Record<string,string>>({name:'',category:'Rings',jewelryType:'',diamondShape:'',metal:'',price:'',currency:'USD',availability:'',leadTime:'',description:'',sku:'',carat:'',color:'',clarity:'',cut:'',certification:'',certificationReference:'',setting:'',stockQuantity:'',provenanceNotes:'',origin:'',images:'',video:'',glb:''});
 useEffect(()=>{if(enabled)fetch('/api/customer/jewellers/inventory').then(r=>r.ok?r.json():null).then(d=>d&&setItems(d.items||[])).catch(()=>{});},[enabled]);
 if(!enabled)return <section className="border border-white/10 p-5"><h2>Inventory</h2><p className="mt-2 text-xs text-[#8f979f]">Available after verification.</p></section>;
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setMessage('');const r=await fetch('/api/customer/jewellers/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,price:form.price?Number(form.price):undefined,carat:form.carat?Number(form.carat):undefined,stockQuantity:form.stockQuantity?Number(form.stockQuantity):undefined,images:form.images.split('\n').map(v=>v.trim()).filter(Boolean)})});const d=await r.json();if(!r.ok){setMessage(d.error||'Could not submit inventory');return;}setItems(v=>[d.item,...v]);setForm({...form,name:'',jewelryType:'',diamondShape:'',metal:'',price:'',availability:'',leadTime:''});setMessage('Submitted for private review.');};
 return <section className="border border-white/10 p-5"><h2>Inventory</h2><p className="mt-2 text-xs text-[#8f979f]">Submit real pieces for private AMES review before publication.</p><form onSubmit={submit} className="mt-5 grid gap-3 sm:grid-cols-2">{[['name','Item name'],['category','Category'],['jewelryType','Jewelry type'],['diamondShape','Diamond shape'],['metal','Metal'],['price','Price'],['currency','Currency'],['availability','Availability'],['leadTime','Delivery information / lead time'],['description','Description'],['sku','SKU / reference'],['carat','Carat (if applicable)'],['color','Color'],['clarity','Clarity'],['cut','Cut'],['certification','Certification'],['certificationReference','Certificate number'],['setting','Setting / style'],['stockQuantity','Stock quantity'],['provenanceNotes','Provenance'],['origin','Origin / source'],['images','Image URLs (main first, one per line)'],['video','Video URL (optional)'],['glb','GLB URL (optional)']].map(([key,label])=><label key={key} className="text-xs text-[#aeb5bc]"><span>{label}</span>{key==='category'?<select value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value}))} className="mt-1 w-full border border-white/20 bg-[#151b20] px-2 py-2">{['Rings','Watches','Bracelets','Necklaces','Earrings'].map(c=><option key={c}>{c}</option>)}</select>:key==='images'?<textarea value={form.images} onChange={e=>setForm(v=>({...v,images:e.target.value}))} className="mt-1 w-full border border-white/20 bg-transparent px-2 py-2"/>:<input required={key==='name'||key==='category'} value={String(form[key as keyof typeof form])} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))} className="mt-1 w-full border border-white/20 bg-transparent px-2 py-2 text-sm text-white" />}</label>)}<button className="border border-white/30 px-4 py-2 text-sm" type="submit">Submit inventory</button></form>{message&&<p className="mt-3 text-xs text-[#dce2ea]">{message}</p>}<div className="mt-6 space-y-2">{items.map(item=><div key={String(item.id)} className="flex justify-between border-t border-white/10 py-2 text-xs"><span>{String(item.name)}</span><span className="text-[#aeb5bc]">{String(item.inventoryStatus)}</span></div>)}</div></section>;
}
