import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {startFixture} from '../tests/appwrite-fixture.mjs';
const {chromium}=createRequire(import.meta.url)(process.env.AMES_PLAYWRIGHT_PATH||'C:/Users/ngwak/Documents/Codex/2026-09-07/github-plugin-github-openai-curated-remote/work/ames-engine/node_modules/playwright');
const f=await startFixture(),origin='http://127.0.0.1:3118';for(const who of ['alice','bob','admin'])f.sessions.set(who+'-session',who);
const put=(table,id,payload,kind,userId='',assetId='')=>f.rows.set(table+':'+id,{$id:id,$permissions:[],kind,userId,assetId,payload:JSON.stringify(payload)});
put('jeweller_sources','alice-atelier',{businessName:'QA verified atelier',email:'alice@example.test',verificationStatus:'VERIFIED',capabilities:{categories:['ring'],languages:['English']}},'JEWELLER_APPLICATION','alice');put('jeweller_sources','bob-atelier',{businessName:'Other atelier',email:'bob@example.test',verificationStatus:'VERIFIED'},'JEWELLER_APPLICATION','bob');
put('analytics_events','sourcing-qa',{status:'OPEN',time:new Date().toISOString(),profile:{category:'ring',shape:'oval',metal:'platinum',budget:5000,currency:'USD',urgency:'This month',language:'English',sourcing_intent:true,location:'South Africa'},notes:'Private customer information'},'SOURCING_REQUEST','private-customer');
put('sourcing_matches','match-qa',{requestId:'sourcing-qa',jewellerId:'alice-atelier'},'SOURCING_MATCH','private-customer','sourcing-qa');
const child=spawn(process.execPath,['node_modules/next/dist/bin/next','start','-p','3118','-H','127.0.0.1'],{env:{...process.env,APPWRITE_ENDPOINT:f.endpoint,APPWRITE_PROJECT_ID:f.project,APPWRITE_API_KEY:f.key,APPWRITE_DATABASE_ID:'ames',AMES_APP_ORIGIN:origin,ASSET_DELIVERY_SECRET:'fixture-only-'.repeat(8)},windowsHide:true,stdio:'ignore'});
let browser,page;const results=[];
const call=(path,method='GET',body,who='alice')=>fetch(origin+'/api/customer/'+path,{method,headers:{origin,...(who?{cookie:'ames_customer='+who+'-session'}:{}),...(body&&!(body instanceof FormData)?{'content-type':'application/json'}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});
let stage='server startup';
try{
 for(let i=0;i<100;i++){try{if((await fetch(origin+'/app')).ok)break;}catch{}await new Promise(r=>setTimeout(r,200));}
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});await mkdir('outputs/sign-in',{recursive:true});page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',()=>errors.push('Browser runtime error'));await page.context().addCookies([{name:'ames_customer',value:'expired-cookie',url:origin}]);await page.goto(origin+'/login');const password=page.getByLabel('Password',{exact:true});
 stage='sign-in toggle';assert.equal(await password.getAttribute('type'),'password');await password.fill(f.password);const before=await password.boundingBox();await page.getByRole('button',{name:'Show password',exact:true}).click();assert.equal(await password.getAttribute('type'),'text');assert.ok(await password.inputValue()===f.password,'Value unchanged');await page.getByRole('button',{name:'Hide password',exact:true}).click();assert.equal(await password.getAttribute('type'),'password');assert.deepEqual(await password.boundingBox(),before);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'outputs/sign-in/mobile.png'});
 stage='incorrect password';await page.getByLabel('Email',{exact:true}).fill('alice@example.test');await password.fill('incorrect-test-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('alert').filter({hasText:'Email or password is incorrect.'}).waitFor();assert.ok(page.url().endsWith('/login'));
 stage='nonexistent account';await page.getByLabel('Email',{exact:true}).fill('nonexistent@example.test');await password.fill(f.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('alert').filter({hasText:'Email or password is incorrect.'}).waitFor();
 stage='fresh administrator sign-in';await page.getByLabel('Email',{exact:true}).fill('admin@example.test');await password.fill(f.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(origin+'/app');const cookie=(await page.context().cookies()).find(c=>c.name==='ames_customer');assert.ok(cookie?.httpOnly);assert.notEqual(cookie.value,'expired-cookie');assert.equal(f.sessions.get(cookie.value),'admin');await page.goto(origin+'/admin');await page.getByRole('navigation',{name:'Admin dashboard'}).waitFor();
 stage='logout destroys session';await page.goto(origin+'/account');await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL(origin+'/app');assert.ok(!f.sessions.has(cookie.value));assert.ok(!(await page.context().cookies()).some(c=>c.name==='ames_customer'));
 stage='verified jeweller sign-in';await page.context().addCookies([{name:'ames_customer',value:'revoked-cookie',url:origin}]);await page.goto(origin+'/login');await page.getByLabel('Email',{exact:true}).fill('alice@example.test');await password.fill(f.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(origin+'/app');await page.goto(origin+'/jewellers/portal');await page.getByRole('navigation',{name:'Jeweller dashboard'}).waitFor();await page.goto(origin+'/admin');await page.getByRole('heading',{name:'Admin access required'}).waitFor();
 stage='registration toggle';await page.context().addCookies([{name:'ames_customer',value:'expired-registration-cookie',url:origin}]);await page.goto(origin+'/login');await page.getByRole('button',{name:'Create account',exact:true}).click();assert.equal(await password.getAttribute('type'),'password');await page.getByLabel('Name',{exact:true}).fill('Registration check');await page.getByLabel('Email',{exact:true}).fill('registration-check@example.test');await password.fill(f.password);const registerBefore=await password.boundingBox();await page.getByRole('button',{name:'Show password',exact:true}).click();assert.equal(await password.getAttribute('type'),'text');await page.getByRole('button',{name:'Hide password',exact:true}).click();assert.equal(await password.getAttribute('type'),'password');assert.deepEqual(await password.boundingBox(),registerBefore);await page.screenshot({path:'outputs/sign-in/mobile-register.png'});
 stage='registration and redirect';await page.getByRole('button',{name:'Create account',exact:true}).click();await page.waitForURL(origin+'/app');const registered=(await page.context().cookies()).find(c=>c.name==='ames_customer');assert.equal(f.sessions.get(registered.value),'registration-check');await page.goto(origin+'/account');await page.getByRole('heading',{name:'Account',exact:true}).waitFor();assert.equal(await page.getByRole('link',{name:'Admin dashboard',exact:true}).count(),0);assert.equal(await page.getByRole('link',{name:'Jeweller dashboard',exact:true}).count(),0);
 stage='desktop';await page.setViewportSize({width:1440,height:1000});await page.goto(origin+'/login');assert.equal(await password.getAttribute('type'),'password');await page.screenshot({path:'outputs/sign-in/desktop.png'});assert.deepEqual(errors,[]);
 const result={staleCookieRecovery:true,wrongPassword:true,nonexistentAccount:true,freshAdminSession:true,verifiedJewellerLogin:true,registration:true,logoutRevokes:true,passwordToggles:true,noToggleLayoutShift:true,mobile:true,browserErrors:errors};console.log(JSON.stringify(result));await writeFile('outputs/sign-in/checks.json',JSON.stringify(result,null,2));
}catch{throw new Error('Sign-in browser validation failed at: '+stage+' (form contents omitted)');}finally{await browser?.close();child.kill();await f.close();}
